import FRSB.Basic
import FRSB.Paper.Definitions
import FRSB.Paper.ExternalInputs
import FRSB.Paper.Theorem1_2
import FRSB.Paper.Theorem_1_3_ZeroTemperatureStructure
import FRSB.ZeroTemperature.Crossing.Proposition_4_1_CrossingRule
import FRSB.ZeroTemperature.SelectedGapConsequences
import FRSB.ZeroTemperature.SelectedSmoothDensity
import FRSB.PositiveTemperature.EndpointAlgebra
import FRSB.PositiveTemperature.EndpointCovariance
import FRSB.PositiveTemperature.EndpointMoments
import FRSB.PositiveTemperature.EndpointIto
import FRSB.PositiveTemperature.SechIntegrals
import FRSB.PositiveTemperature.StrictCovariance
import FRSB.ZeroTemperature.SlopeAlgebra
import FRSB.ZeroTemperature.SupportAssembly
import FRSB.ZeroTemperature.Foundations.TransformedDensity
import FRSB.ZeroTemperature.QDynamics.Lemma_3_5_HeatCancellation
import FRSB.ZeroTemperature.QDynamics.Lemma_3_5_JumpRule
import FRSB.ZeroTemperature.QDynamics.Lemma_3_5_Heat
import FRSB.ZeroTemperature.QDynamics.Lemma_3_5_HeatRegion
import FRSB.ZeroTemperature.QDynamics.Lemma_3_5_Jump
import FRSB.ZeroTemperature.QDynamics.Proposition_3_7_LogDerivativeIdentity
import FRSB.ZeroTemperature.QDynamics.Proposition_3_7_LogDerivativeFunctional
import FRSB.ZeroTemperature.NoInternalGap.Proposition_4_2_StrictMoment
import FRSB.ZeroTemperature.NoInternalGap.Proposition_4_2_GapContradiction
import FRSB.ZeroTemperature.NoInternalGap.Proposition_4_2_WeightedSecond
import FRSB.ZeroTemperature.NoInternalGap.Proposition_4_2_WeightedSecondZero
import FRSB.ZeroTemperature.NoInternalGap.Proposition_4_2_IntervalClosed
import FRSB.ZeroTemperature.Smoothness.Proposition_4_4_RightContinuousRepresentative
import FRSB.ZeroTemperature.Smoothness.Proposition_4_4_QuotientRegularity
import FRSB.ZeroTemperature.Smoothness.Proposition_4_4_BootstrapToSmooth
import FRSB.ZeroTemperature.Smoothness.Proposition_4_4_MomentQuotientBootstrap
import FRSB.ZeroTemperature.Smoothness.Proposition_4_4_AERepresentativeOnInterval
import FRSB.ZeroTemperature.AppendixA.Proposition_A_3_KAverage
import FRSB.ZeroTemperature.AppendixA.Proposition_3_9_ParameterDecrease
import FRSB.ZeroTemperature.AppendixA.Proposition_3_9_InitialLogCosh
import FRSB.ZeroTemperature.AppendixA.Lemma_A_1_SlopeLinearCoefficient
import FRSB.ZeroTemperature.AppendixA.Lemma_A_1_LogCoshEndpointExpansion
import FRSB.ZeroTemperature.AppendixA.Lemma_A_1_LogCoshDifferentiatedRemainder
import FRSB.ZeroTemperature.AppendixA.Lemma_A_1_LogCoshDifferentiatedBounds
import FRSB.ZeroTemperature.AppendixA.Lemma_A_1_LogCoshZerothRemainderBound
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_InteriorMinimumContradiction
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_DegenerateStripComparison
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_SpatialFermat
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_SpatialSecondDerivative
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_TimeDerivative
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_DegenerateStripComparisonComplete
import FRSB.ZeroTemperature.AppendixA.Lemma_A_2_ExponentialTransformation
import FRSB.ZeroTemperature.AppendixB.Lemma_3_12_UniformTailDriftBracket
import FRSB.ZeroTemperature.AppendixB.Lemma_3_3_GlobalGradientDifferenceQuotient
import FRSB.ZeroTemperature.AppendixB.Lemma_3_3_SecondDerivativeToGlobalGradient
import FRSB.ZeroTemperature.AppendixB.Lemma_3_12_SignDefectTailBracket
import FRSB.ZeroTemperature.AppendixB.Lemma_3_4_ThirdDerivativeSignLimit
import FRSB.ZeroTemperature.AppendixB.Lemma_3_4_RegularizedTerminalThirdDerivative
import FRSB.ZeroTemperature.AppendixB.Lemma_3_13_MomentGeneratorRegularity
import FRSB.ZeroTemperature.AppendixB.Lemma_3_13_FiniteMomentCombinationRegularity
import FRSB.ZeroTemperature.AppendixB.Lemma_3_13_ItoIntegralToGeneratorRegularity
import FRSB.ZeroTemperature.AppendixB.Lemma_3_13_IntervalMomentRegularity
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_CofinalFromNoTerminalGap
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_SupportClosedBelowOne
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_TerminalSquareRootContradiction
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_DominatedBoundaryScaling
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_TerminalDeficitAsymptotic
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianBoundaryFactor
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianDensitySquareIntegral
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianCDFDerivative
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianCDFProductDerivative
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianCDFFiniteIntervalIntegral
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianCDFSymmetryAndDecay
import FRSB.ZeroTemperature.NoTerminalGap.Proposition_4_3_GaussianCDFWholeLineIntegral
import FRSB.ZeroTemperature.Smoothness.Proposition_4_4_StieltjesIntervalMass

/-!
# FRSB

Root module for the Lean verification project associated with
`frsb_sk_full_interval_zero_temperature_arxiv_v15.32.tex`.

The exact conclusions of Theorems 1.2 and 1.3 are transcribed in separate
files.  Their final Lean theorems are explicitly conditional assembly results:
the manuscript's internal PDE and stochastic-analysis arguments have not yet
been formalized.  `FORMALIZATION_STATUS.md` records this boundary and the sole
external-literature axiom.
-/
